/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:59385815-9f14-44d2-9093-47614ff7a88e",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_Ji0NyKMT2",
    "aws_user_pools_web_client_id": "70t4fdsbcn9aqfnb35qnbf463s",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "topicapi",
            "endpoint": "https://lhwotrqat2.execute-api.ap-northeast-2.amazonaws.com/stanjjang",
            "region": "ap-northeast-2"
        }
    ]
};


export default awsmobile;
